<a href="https://colab.research.google.com/github/Mariett-7/Programaci-n-I/blob/main/bono_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manejo de módulos integrados

NumPy: se usa principalmente para trabajar con datos númericos de forma rápida, eficiente y estructurada. Un objeto tipo NumPy es un arreglo base para hacer matemáticas y manipular datos en Phyton.

Pandas: se usa para trabajar con datos estructurales (Como tablas de Excel o bases de datos). Un objeto tipo pandas permite cargar, limpiar, transformar y analizar datos. Lo usamos para bases de datos relacionales.

La diferencia entre NumPy y Pandas radica en su propósito y nivel de uso: NumPy es una liberia enfocada en el cálculo numérico eficiente mediante arrays multidimensionales, ideal para operaciones matemáticas rápidas, álgebra lineal y procesamiento de datos puramente numéricos; mientras que Pandas es una libreria de más alto nivel diseñada para la manipulación y análisis de datos estructurados, como tablas tipo Excel o bases de datos, permitiendo trabajar con columnas con nombres, datos de distintos tipos, limpieza, filtrado y agrupación; en la práctica, Pandas se apoya internamente de NumPy, por lo que ambos se complementan y se utilizan juntos en la mayoria de flujos de ciencia de datos.

In [1]:
import numpy as np #Importar el paquete numpy como np

Creando arreglos:

In [2]:
a = np.array([3, 21, 6, 5])
b = np.array([[24, 4], [74, 8]])
print(a)
print(b)

[ 3 21  6  5]
[[24  4]
 [74  8]]

In [3]:
a = np.array([2, 6, 6, 8])
b = np.array([[2,11], [-5, 8], [7, 4]])
print(a)
print(b)

[2 6 6 8]
[[ 2 11]
 [-5  8]
 [ 7  4]]

In [4]:
b*3 #Toma la matriz y multiplica cada elemento dentro de la matriz por 2

array([[  6,  33],
       [-15,  24],
       [ 21,  12]])

In [8]:
lista = [1, 5, 43] #Objetos que no son inmutables, es decir, se pueden intercambiar los elementos dentro de una lista y podemos indemzar cada elemento de la lista
arr = np.array([1, 5, 43])

In [9]:
lista*2 #Lista concatenada, es decir, voy a tener la lista obtenida antes 2 veces escrita

[1, 5, 43, 1, 5, 43]

In [10]:
arr*2 #Hay una interpretación de los arreglos tipo numpy más apegados a lo que vemos de los #obejtos matemáticos como los vectores

array([ 2, 10, 86])

In [11]:
arr.shape #Forma (Dimensiones) del objeto trabajado

(3,)

In [ ]:
b.shape #Arreglo de tres componentes cada uno con dos elementos

(3, 2)

In [ ]:
arr.ndim #Número de dimensiones

1

In [ ]:
b.ndim #Número de elementos por cada componente

2

In [ ]:
b.dtype #Tipo de dato

dtype('int64')

In [ ]:
b.size #Cantidad de elementos en todas las componentes

6

Arreglos especiales:

In [12]:
np.zeros((2,3)) #Todo lleno de ceros: 2 componentes y 3 elementos por componente - Arreglo de ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2)) #Todo lleno de ceros: 4 componentes y 2 elementos por componente - Arreglo de unos

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.eye(6) #La matriz identidad de una matriz cuadrada de tamaño 6 - Arreglo de la matriz identidad

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.arange(0, 45, 9) #Del 0 hasta el 45 (sin tomar el 45), separado por 9

array([ 0,  9, 18, 27, 36])

In [18]:
np.linspace(0,3,7) #5 elementos equidistantes entre el 0 y el 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [ ]:
arry = np.array([30, 40, 60, 80]) #Llamar la función del módulo
arry[0]

np.int64(30)

In [ ]:
arry[-1]

np.int64(80)

In [ ]:

arry[0:2] #Tomando de índice del 0 al 2 (sin tomar el 2)

array([10, 20])

Indexación de matrices:

Matri= (2 4 6
        8 10 12) y es nuestro objeto matemático
        
        Matri[0,1]=4

        Matri[:,1]=(4,10)

        Matri[1,:]=(8,10,12)*texto en cursiva*

In [ ]:
matri = np.array([[2,4,6],[8,10,12]]) #Definición de Matriz

In [ ]:
matri[0,1] #El índice 1 de la ceroésima fila - Elemento 0,1

np.int64(4)

In [ ]:
matri[:,1]

array([ 4, 10])

In [ ]:
matri[:,0] #

array([2, 8])

In [ ]:
matri[1,:]

array([ 8, 10, 12])

In [ ]:
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])
a + b

#Sumar componente a componente

array([10, 14, 18])

In [ ]:
a*b
#Multiplicar componente a componente

array([16, 40, 72])

In [ ]:
matri1 = np.array([[2,6,3],[4,7,6]]) #Definición de Matriz 1
matri1*matri #Producto de Hadamard es decir producto componente a componente

array([[ 4, 24, 18],
       [32, 70, 72]])

In [ ]:
[x * 2 for x in lista] #Lento

[4, 14, 26]

In [ ]:
arr * 2 #Rápido

array([ 4, 14, 26])

Funciones Estadísticas implementadas:

In [ ]:
c=np.array([1.60, 1.57, 1.81, 1.80, 1.90, 1.86, 1.72])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))
#Determina la media, la mediana, la desviación estándar, el total, el valor mínimo, el valor máximo

1.7514285714285713 1.8 0.11740389035031058 12.26 1.57 1.9

Manipulación de Arreglos:

In [ ]:
d = np.array([ 2, 3, 4, 5, 6, 7]) #Cambiar formas
d.reshape(2,3)
#Inicialmente,tien seis componentes de un elemento cada una
#El primer argumento me dice el número de componentes, cambia a dos componentes cada una con tres elementos

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
np. concatenate([d, a]) #Concatenar arreglos, es decir a un arreglo le pego otro

array([2, 3, 4, 5, 6, 7, 2, 4, 6])

In [ ]:
np. concatenate(d.reshape(2,3))

array([2, 3, 4, 5, 6, 7])

In [ ]:
d.reshape(2,3).flatten() #Vectoriza la matriz

array([2, 3, 4, 5, 6, 7])

In [ ]:
a = np.array([[4, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]]) #Producto punto - Multiplicación de matrices

np.dot(a, b)

array([[34, 40],
       [43, 50]])

In [ ]:
np.linalg.det(a) #Determinante - Funciones de álgebra lineal y se calcula el determinante de una matriz

np.float64(10.000000000000002)

In [ ]:
np.linalg.inv(a) #Inversa de una matriz

array([[ 0.4, -0.2],
       [-0.3,  0.4]])

In [ ]:
np.linalg.matrix_transpose(a) #Traspuesta de una matriz

array([[4, 3],
       [2, 4]])

In [ ]:
np.random.rand(10) #Números aleatorios entre cero y uno
#Es decir genera 10 valores aletarorios de una distribución uniforme en el intervalo (0,1)

array([0.81395373, 0.25637324, 0.4469276 , 0.10850192, 0.08679687,
       0.73236863, 0.78201614, 0.8813208 , 0.87947739, 0.66572012])

In [ ]:
np.random.randint(0,10) #Genera un valor entero entre 0 y el anterior al 10
#Un valor de la distribución uniforme discreta

2

In [ ]:
np.random.randn(8) #Genera 8 valores aleatorios de una distribución normal con media 0 y
#Desviación estándar 1

array([ 1.72245367,  1.26928476, -0.32046706, -0.04479192,  1.39373919,
        0.9999128 , -0.40175649,  0.38033306])

In [ ]:
e = np.array([1, 2, 3, 4, 5]) #Filtrado y condiciones
f = e[e > 3]
f

array([4, 5])

In [ ]:
e[(e > 2) & (e < 5)] #Note que el y es así &. El o es así |

array([3, 4])

In [ ]:
np.where(e > 3, 1, 0) #donde e > 3 anotamos un 1, y donde no, anotamos un 0

array([0, 0, 0, 1, 1])

In [ ]:
np.where(e > 3, 1, e) #Los valores que no queremos reemplazar, anotamos el mismo objeto

array([1, 2, 3, 1, 1])

Ahora con Pandas

Importamos el paquete de Pandas

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([40, 60, 80]) #Vector columna
s
#Pandas es un objeto tipo tabla

0    40
1    60
2    80
dtype: int64

In [ ]:
df = pd.DataFrame({ 'nombre': ['Angie', 'Gabriela', 'Camilo', 'Marta'],
                   'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
                    'edad': [24, 31, 36, 29],
                    'salario': [1500, 2000, 2500, 3000]
                    }) #Creando data.frames y es un objeto tipo Diccionario
df

     nombre    ciudad  edad  salario
0     Angie    Bogotá    24     1500
1  Gabriela  Medellín    31     2000
2    Camilo      Cali    36     2500
3     Marta    Bogotá    29     3000

In [ ]:
average_salary_by_city = df.groupby('ciudad')['salario'].mean()
display(average_salary_by_city)

ciudad
Bogotá      2250.0
Cali        2500.0
Medellín    2000.0
Name: salario, dtype: float64

In [ ]:
df.head() #primeras filas
#Nos da los primeros 4 datos de nuestra base de datos

     nombre    ciudad  edad  salario
0     Angie    Bogotá    24     1500
1  Gabriela  Medellín    31     2000
2    Camilo      Cali    36     2500
3     Marta    Bogotá    29     3000

In [ ]:
df.tail(2) #Últimas filas
#Nos muestras las dos últimas filas de nuestra base de datos

   nombre  ciudad  edad  salario
2  Camilo    Cali    36     2500
3   Marta  Bogotá    29     3000

In [ ]:
df.info() #Tipo de datos
#Nos muestra cada una de las columnas, sí hay elementos nulos, es decir, datos faltantes y el tipo de objeto
#Los primeros objetos son cadenas, pueden ser texto o pueden ser elementos de tipo buleano

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe() #Estadísticas
#Que hace el método describe estadísticas descriptivas básicas para variables cuantitativas

            edad      salario
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

In [ ]:
df.shape #(filas, columnas)
#El método shape nos dice el número de filas y el número de columnas que tiene mi base de datos

(4, 4)

In [ ]:
salario_promedio = df['salario'].mean()
print( f"El salario_promedio: {salario_promedio}")
#

El salario_promedio: 2250.0

In [ ]:
df['edad'] #Para imprimir la columna edad

0    24
1    31
2    36
3    29
Name: edad, dtype: int64

In [ ]:
df[['nombre', 'edad']] #Selección de columnas, utilizando una lista con los respectivos nombres

     nombre  edad
0     Angie    24
1  Gabriela    31
2    Camilo    36
3     Marta    29

In [ ]:
df[df['edad'] >25] #Selección de filas, es decir las personas que tengan más de 25 años

     nombre    ciudad  edad  salario
1  Gabriela  Medellín    31     2000
2    Camilo      Cali    36     2500
3     Marta    Bogotá    29     3000

In [ ]:
df[(df['edad'] > 20) & (df['edad']  < 40)] #Las personas que tengan más de 20 años, pero que sean menores de 40 años

     nombre    ciudad  edad  salario
0     Angie    Bogotá    24     1500
1  Gabriela  Medellín    31     2000
2    Camilo      Cali    36     2500
3     Marta    Bogotá    29     3000

In [ ]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
        'edad': [23, np.nan, 35, 23, 40],
        'salario': [1000, 2000, None, 1000, 5000],
        'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
    }
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
 'edad': [23, nan, 35, 23, 40],
 'salario': [1000, 2000, None, 1000, 5000],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [ ]:
data1 = pd.DataFrame(data) #Así tranformamos un diccionario en una tabla de Pandas
data1

   nombre  edad  salario    ciudad
0     Ana  23.0   1000.0    Bogotá
1    Luis   NaN   2000.0  Medellín
2  Carlos  35.0      NaN      Cali
3     Ana  23.0   1000.0    Bogotá
4    None  40.0   5000.0      Cali

In [ ]:
data1.isnull() #Valores Faltantes
#El médoto isnull, muestra true si el valor es faltante y false si el valor no es faltante

   nombre   edad  salario  ciudad
0   False  False    False   False
1   False   True    False   False
2   False  False     True   False
3   False  False    False   False
4    True  False    False   False

In [ ]:
data1.isnull().sum() #El método sum, suma los valores por columnas: 1 si es faltante, 0 si no.

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [ ]:
data2 = data1.dropna() #El modelo Dropna, elimina las filas con valores faltantes
data2

  nombre  edad  salario  ciudad
0    Ana  23.0   1000.0  Bogotá
3    Ana  23.0   1000.0  Bogotá

In [ ]:
data1.dropna(subset=['salario']) #Se eliminan las filas con valores faltantes, únicamente
#en la columna salario

  nombre  edad  salario    ciudad
0    Ana  23.0   1000.0    Bogotá
1   Luis   NaN   2000.0  Medellín
3    Ana  23.0   1000.0    Bogotá
4   None  40.0   5000.0      Cali

In [ ]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean())
data1['nombre'] = data1['nombre'].fillna('Desconocido')
data1
#Se están imputando datos faltantes, es decir que ponga la media aritmética de la columna de edad de data1
#Con la columna nombre la esta reemplazando con la misma columna nombre, pero a los valores faltantes les pone desconocido

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    Bogotá
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    Bogotá
4  Desconocido  40.00   5000.0      Cali

In [ ]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1
#El modelo replace o reemplazo, lo que hace es reemplazar la palabra Bogotá por BOGOTA en Mayúscula, en la columna ciudad
#de data1

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    BOGOTA
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    BOGOTA
4  Desconocido  40.00   5000.0      Cali

In [ ]:
data4 = data1['ciudad'].drop_duplicates()
data4
#Se toma data1 sin duplicados

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [ ]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis'],
        'edad': [23, 30, 23, 35, 30],
        'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín', 'Cali']
    }
data5 = pd.DataFrame(data5)
data5

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
2     Ana    23    Bogotá
3  Carlos    35  Medellín
4    Luis    30      Cali

In [ ]:
data6 = data5.drop_duplicates()
data6
#Aquellos valores que tengang duplicados, pues no los considera

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
3  Carlos    35  Medellín

In [ ]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': ['Ana', 'LUIS', 'Carlos', 'ana'],
        'edad': [23, 30, 35, 28],
        'salario': [1000, 2000, 3000, 1500],
        'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
    })
dfn

   id  nombre  edad  salario    ciudad
0   1     Ana    23     1000    Bogotá
1   2    LUIS    30     2000      Cali
2   3  Carlos    35     3000    Bogotá
3   4     ana    28     1500  Medellín

In [ ]:
dfn['salario_anual'] = dfn['salario'] * 12 #aplicar función
dfn['edad_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn
#Estamos agregando una nueva columna: una que es el salario anual y la otra que es el doble de la edad

   id  nombre  edad  salario    ciudad  salario_anual  edad_doble
0   1     Ana    23     1000    Bogotá          12000          46
1   2    LUIS    30     2000      Cali          24000          60
2   3  Carlos    35     3000    Bogotá          36000          70
3   4     ana    28     1500  Medellín          18000          56

In [ ]:
dfn = dfn.rename(columns= {'edad': 'age'}) #Renombrar columnas, entonces la columna edad la renombra como edad en inglés
dfn

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1     Ana   23     1000    Bogotá          12000          46
1   2    LUIS   30     2000      Cali          24000          60
2   3  Carlos   35     3000    Bogotá          36000          70
3   4     ana   28     1500  Medellín          18000          56

In [ ]:
dfn['nombre'] = dfn['nombre'].str.upper() #Convierte al objeto en letras mayúsculas como son las cadenas del nombre
dfn['nombre'] = dfn['nombre'].str.strip() #Limpia las cadenas del nombre y eliminando los espacios en blanco
dfn['nombre'] = dfn['nombre'].str.replace('ANA', 'JOANA') #Replace reemplaza a ana por ANA

In [ ]:
dfn

   id    nombre  age  salario    ciudad  salario_anual  edad_doble
0   1  JJOJOANA   23     1000    Bogotá          12000          46
1   2      LUIS   30     2000      Cali          24000          60
2   3    CARLOS   35     3000    Bogotá          36000          70
3   4  JJOJOANA   28     1500  Medellín          18000          56

In [ ]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo
#Este método toma la columna ciudad y todos los elementos de la columna salario, para calcular la media aritmética del salario
#Agrupa todos los elementos de ciudad y calcula a esos grupos la media aritmética

ciudad
Bogotá      2000.0
Cali        2000.0
Medellín    1500.0
Name: salario, dtype: float64

In [ ]:
ordenado = dfn.sort_values(by= 'age')
ordenado
#Ordenar los datos de la base de datos

   id    nombre  age  salario    ciudad  salario_anual  edad_doble
0   1  JJOJOANA   23     1000    Bogotá          12000          46
3   4  JJOJOANA   28     1500  Medellín          18000          56
1   2      LUIS   30     2000      Cali          24000          60
2   3    CARLOS   35     3000    Bogotá          36000          70

In [ ]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
    })

merge = pd.merge(dfn, dfn1, on= 'id')
merge

,id,nombre,age,salario,ciudad,salario_anual,edad_doble,departamento
0,1,JJOJOANA,23,1000,Bogotá,12000,46,Ventas
1,2,LUIS,30,2000,Cali,24000,60,IT
2,3,CARLOS,35,3000,Bogotá,36000,70,RRHH
3,4,JJOJOANA,28,1500,Medellín,18000,56,Marketing

In [ ]:
valores = dfn.values
valores
#Sí se quiere cambiar un objeto tipo Pandas a un objeto tipo NumPy, usamos el método values

array([[1, 'JJOJOANA', 23, 1000, 'Bogotá', 12000, 46],
       [2, 'LUIS', 30, 2000, 'Cali', 24000, 60],
       [3, 'CARLOS', 35, 3000, 'Bogotá', 36000, 70],
       [4, 'JJOJOANA', 28, 1500, 'Medellín', 18000, 56]], dtype=object)

In [ ]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df
#Sí se quiere cambiar un objeto tipo NumPy a un objeto tipo Pandas, usamos el método DataFrame

    0
0  10
1  20
2  30